/* The verified fact sheet behind the AI Twin and the Hiring Agent's writing
   step. Only what the résumé and the case studies state; nothing else. */
export const FACTS = `- AI Product Manager based in Chennai, India. 9+ years (since May 2016) across software engineering, digital products and enterprise AI; product roles since March 2020. Open to senior AI product roles (AI Product Manager, Technical Product Manager, AI Product Owner) in Bengaluru, Hyderabad, Dubai or remote.
- AT&T, Aug 2022 to present, AI Technical Business Analyst (Product Manager), Consumer Technology & Experience. End-to-end product owner of AT&T's GenAI virtual assistant on Google CCAI / Dialogflow across chat, voice, WhatsApp and RCS: 1.5M+ monthly customer interactions, 350+ intents, 1,200+ training phrases, RAG-powered knowledge retrieval, human-in-the-loop review for low-confidence answers, 55% containment, 28% fewer live-agent escalations, an estimated $4.2M in annual operational savings, 32 seconds lower average handle time through telephony and CRM integration, 92% intent-recognition accuracy, NPS up 8 points, 15+ KPIs tracked in Power BI and SQL. Owned backlog and sprint planning for 2 squads (18 developers) in SAFe with 95% sprint-commitment reliability; helped secure a $2.5M FY25 budget. Also: Retail Hyper-Personalization (+15% recommendation click-through) and an AI Performance Analytics Suite covering 15+ KPIs across 6 channels.
- Verizon, Mar 2020 to Aug 2022, Consultant, Digital & Assisted Sales: funnel analysis, A/B testing and customer research across retail, consumer and B2B; requirements for 15+ features at 94% on-time delivery; $1.5M+ incremental revenue in FY21. Omni Universal Cart (+11% order fulfillment, -13% cart abandonment), 3-Year Device Payment Plans ($320K pilot revenue, +14% upgrade rate), Early Termination Fee redesign (-22% service inquiries), Hum+ Wi-Fi add-on ($100K+ ARR, 23% attach), Split Fulfillment (2.1 days faster delivery, +3 CSAT).
- Infosys, May 2016 to Feb 2020, Senior Software Engineer: modernized Boeing's Work Statement Requirement Database for 1,200+ maintenance engineers across 5 facilities; 6 major releases; 99.2% uptime; an estimated $2.8M in annual savings.
- DeviceFlex (AT&T Sprint-a-thon 2026): conceived, designed and built solo a working prototype that reimagines device protection as an AI-powered membership (AI-guided claims, household protection score, same-day swaps, a data vault). Principle: AI perceives, deterministic functions decide. Invention disclosure submitted to AT&T's patent program.
- Awards: AT&T Innovation Jam 2026 Best in Show / All Around (AT&T Helios, a one-click converged bundle experience); AT&T Hackathon 2025 1st place (hyper-personalized international travel); Equitech Hackathon 2025 Most Impactful Business Solution; AT&T Connection Award 2023 with the virtual assistant team; Verizon Spotlight Award 2021 for Customer Excellence.
- Independent AI builds: Crosscheck (enterprise knowledge contradiction auditor, Microsoft Agents League hackathon), ClimaTwin (urban climate decision intelligence on Gemini, BigQuery ML and Earth Engine, Google Gen AI Academy APAC; live demo and 3-minute video), NebulaX (self-correcting agent swarm; 3-minute video), FourCast (grounded video-captioning agent, AMD hackathon team project), MatchDay Ops (explainable stadium operations AI; live demo).
- This site: an AI Twin (this chat) that answers from this fact sheet and can take actions, and a Hiring Agent that maps a job description to evidence, scores fit deterministically, drafts outreach and prepares a calendar invite.
- Education: B.E. Mechanical Engineering, Velammal Engineering College (Anna University), 2012 to 2016, distinction.
- Certifications: SAFe 6 Lean Portfolio Manager (2024), SAFe 6 Agilist and SAFe PO/PM (2023), Microsoft Azure AI Fundamentals (2023), Certified Scrum Product Owner (2022).
- Contact: ashfaque_rifaye@outlook.com or linkedin.com/in/ashfaque-rifaye.`;
